const assert=require('node:assert/strict');
const {plan,formula,OLD_IMPORT}=require('../scripts/lead-cutover-plan.cjs');
const string=v=>({effectiveValue:{stringValue:v}});
const row=Array.from({length:23},()=>({}));row[19]=string('L012');
for(const c of [3,4,5,6,22])row[c]={userEnteredValue:{formulaValue:formula(5,c)}};
row[8]={userEnteredValue:{numberValue:50}};row[11]={userEnteredValue:{numberValue:50}};
const input={sheets:[{sheetId:1600000002,title:'סנכרון לידים'},{sheetId:1436915665,title:'משתתפי מרתונים'}],importFormula:OLD_IMPORT,lookupRows:[['L012 | בדיקה','L012','בדיקה','0500000000','בית ספר','ז','','חדש'].map(string)],participantRows:[row],sourceReady:true};
const before=JSON.stringify(input);const result=plan(input);assert.equal(JSON.stringify(input),before);
assert.equal(result.summary.historicalRegistrations,1);assert.equal(result.summary.archiveLeads,1);
const writes=result.requests.filter(r=>r.updateCells?.start.sheetId===1436915665);
assert.deepEqual(writes.map(r=>r.updateCells.start.columnIndex),[3,4,5,6,22]);
assert.ok(writes.every(r=>r.updateCells.rows[0].values[0].userEnteredValue.formulaValue.includes('ארכיון לידים')));
assert.throws(()=>plan({...input,sourceReady:false}),/headers/);
assert.throws(()=>plan({...input,importFormula:'other'}),/Unexpected/);
assert.throws(()=>plan({...input,lookupRows:[]}),/No archive/);
assert.throws(()=>plan({...input,lookupRows:[...input.lookupRows,...input.lookupRows]}),/Duplicate/);
const changed=structuredClone(row);changed[3]={userEnteredValue:{formulaValue:'=42'}};
assert.throws(()=>plan({...input,participantRows:[changed]}),/Unexpected participant/);
console.log('PASS atomic archive cutover plan, financial/ID preservation, changed-state guards');
