import {test} from 'node:test';import assert from 'node:assert/strict';import {handleRequest} from '../src/worker.mjs';
const env={MARATHON_SCRIPT_URL:'https://example.test/marathon',MARATHON_GATEWAY_SECRET:'secret',TURNSTILE_SECRET:'ts',TURNSTILE_EXPECTED_HOSTNAMES:'ohadmath12.github.io',REGISTRATION_RATE_LIMITER:{limit:async()=>({success:true})}};
function req(body){return new Request('https://worker.test/api/marathon',{method:'POST',headers:{Origin:'https://ohadmath12.github.io','Content-Type':'text/plain'},body:JSON.stringify(body)});}
test('catalog only returns public event fields',async()=>{const r=await handleRequest(new Request('https://worker.test/api/marathons'),env,async(url,opts)=>{assert.equal(JSON.parse(opts.body).payload.operation,'marathon_catalog');return Response.json({ok:true,events:[{id:'m1',name:'אירוע',price:80,phone:'private',notes:'private'}]});});assert.deepEqual(await r.json(),{ok:true,events:[{id:'m1',name:'אירוע',price:80}]});});
test('marathon route verifies correct challenge and strips forged operations',async()=>{let calls=0;const r=await handleRequest(req({turnstile_token:'token',client_submission_id:'test',event_id:'m1',quoted_price:80,operation:'privileged',gateway_secret:'forged',status:'paid'}),env,async(url,opts)=>{calls++;if(url.includes('siteverify'))return Response.json({success:true,hostname:'ohadmath12.github.io',action:'marathon'});const data=JSON.parse(opts.body);assert.equal(data.gateway_secret,'secret');assert.equal(data.payload.operation,'marathon_intake');assert.equal(data.payload.status,undefined);assert.equal(data.payload.gateway_secret,undefined);return Response.json({ok:true,student_id:'private'});});assert.equal(calls,2);assert.deepEqual(await r.json(),{ok:true});});
test('wrong challenge does not reach storage',async()=>{let calls=0;const r=await handleRequest(req({turnstile_token:'t'}),env,async()=>{calls++;return Response.json({success:true,hostname:'ohadmath12.github.io',action:'registration'});});assert.equal(r.status,403);assert.equal(calls,1);});
test('honeypot is verified then discarded',async()=>{let calls=0;const r=await handleRequest(req({turnstile_token:'t',honeypot:'bot'}),env,async()=>{calls++;return Response.json({success:true,hostname:'ohadmath12.github.io',action:'marathon'});});assert.equal(calls,1);assert.deepEqual(await r.json(),{ok:true});});
test('errors are generic; expired quote is explicit',async()=>{const r=await handleRequest(req({turnstile_token:'t'}),env,async(url)=>url.includes('siteverify')?Response.json({success:true,hostname:'ohadmath12.github.io',action:'marathon'}):Response.json({ok:false,code:'event_changed',private:'secret'}));assert.equal(r.status,409);assert.equal((await r.json()).code,'event_changed');});
test('null, oversized, foreign-origin and missing secret requests fail closed',async()=>{const noFetch=()=>{throw Error('must not fetch');};assert.equal((await handleRequest(req(null),env,noFetch)).status,400);assert.equal((await handleRequest(req({x:'x'.repeat(9000)}),env,noFetch)).status,413);assert.equal((await handleRequest(new Request('https://worker.test/api/marathons',{headers:{Origin:'https://evil.test'}}),env,noFetch)).status,403);assert.equal((await handleRequest(req({}),{...env,MARATHON_GATEWAY_SECRET:''},noFetch)).status,503);});
