const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const c={console,Date,Utilities:{formatDate:d=>d.toISOString().slice(0,10),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()]},SpreadsheetApp:{flush(){}}};vm.createContext(c);vm.runInContext(fs.readFileSync('marathon-script/Intake.gs','utf8')+'\n'+fs.readFileSync('marathon-script/Admin.gs','utf8'),c);
class Sheet{constructor(rows){this.rows=rows;this.failAfter=false;}getLastRow(){return this.rows.length;}getMaxRows(){return 1000;}getRange(r,col=1,n=1,w=1){if(typeof r==='string'){const m=r.match(/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/);r=+m[2];col=m[1].charCodeAt(0)-64;n=+m[4]-r+1;w=m[3].charCodeAt(0)-64-col+1;}const sh=this;return {getFormulas(){return Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>typeof sh.rows[r+i-1]?.[col+j-1]==='string'&&sh.rows[r+i-1][col+j-1].startsWith('=')?sh.rows[r+i-1][col+j-1]:''));},getValue(){return sh.rows[r-1]?.[col-1]??'';},getValues(){return Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>sh.rows[r+i-1]?.[col+j-1]??''));},setValues(v){assert.equal(v.length,n);for(let i=0;i<n;i++){assert.equal(v[i].length,w);sh.rows[r+i-1]??=[];for(let j=0;j<w;j++)sh.rows[r+i-1][col+j-1]=v[i][j];}if(sh.failAfter){sh.failAfter=false;throw Error('temporary write response failure');}return this;},clearDataValidations(){return this;},setNumberFormat(){return this;},setNote(){return this;}};}}
function fixture(){const ev=['מרתון בדיקה',new Date('2099-01-01'),'ט','בדיקה',80,'הרשמה פתוחה','internal secret note','group1','group1 | בדיקה','event1',6];const es=new Sheet([[],[],[],[],ev]),ps=new Sheet([[],[],[],[]]),ls=new Sheet([['מזהה בקשה']]);const campaign=['event1','מרתון בדיקה','ט','חטיבת בראשית, גני תקווה',80,'הרשמה פתוחה',''];const cs=new Sheet([[],[],[],[],campaign]);const ss={getSheetByName:n=>n==='מרתונים'?es:n==='מרתונים להרשמה'?cs:n==='משתתפי מרתונים'?ps:ls};return{ss,es,ps,ls,ev,campaign,cs};}
function payload(over={}){return{client_submission_id:crypto.randomUUID(),event_id:'event1',quoted_price:80,student_first_name:'בדיקת',student_last_name:'מערכת',school_name:'חטיבת בראשית, גני תקווה',class_name:'ט',units:'הקבצה א',parent_name:'הורה בדיקה',parent_phone:'0500000000',...over};}
{const f=fixture(),p=c.mwNormalize_(payload());c.mwIntake_(f.ss,p);assert.equal(f.ps.rows.length,5);assert.equal(f.ps.rows[4][8],80);assert.equal(f.ps.rows[4][17],'ממתין לשיבוץ');assert.equal(f.ps.rows[4][18],'');assert.equal(f.ps.rows[4][23],'event1');assert.equal(f.ps.rows[4][11],'');assert.equal(f.ls.rows[1][13],'נקלט');c.mwIntake_(f.ss,p);assert.equal(f.ps.rows.length,5);assert.throws(()=>c.mwIntake_(f.ss,{...p,first:'changed'}),/receipt_mismatch/);c.mwIntake_(f.ss,c.mwNormalize_(payload()));assert.equal(f.ps.rows.length,5);assert.equal(f.ls.rows[2][13],'כבר רשום');c.mwIntake_(f.ss,c.mwNormalize_(payload({student_first_name:'אחות'})));assert.equal(f.ps.rows.length,6);c.mwIntake_(f.ss,c.mwNormalize_(payload({parent_phone:'0500000001'})));assert.equal(f.ps.rows.length,6);assert.equal(f.ls.rows[4][13],'נדרש בירור');}
for(const mutate of [f=>f.campaign[5]='הרשמה סגורה',f=>f.campaign[4]=100]){const f=fixture();mutate(f);assert.throws(()=>c.mwIntake_(f.ss,c.mwNormalize_(payload())),/event_changed/);assert.equal(f.ps.rows.length,4);assert.equal(f.ls.rows.length,1);}
{const f=fixture(),p=c.mwNormalize_(payload());f.ps.failAfter=true;assert.throws(()=>c.mwIntake_(f.ss,p),/temporary/);assert.equal(f.ps.rows.length,5);assert.equal(f.ls.rows[1][13],'ממתין');f.ev[4]=100;c.mwIntake_(f.ss,p);assert.equal(f.ps.rows.length,5);assert.equal(f.ls.rows[1][13],'נקלט');}
for(const class_name of ['ד','ה','ו','יג',''])assert.throws(()=>c.mwNormalize_(payload({class_name})),/invalid_study/);
for(const class_name of ['ז','ח','ט','י','י״א','י״ב'])assert.equal(c.mwNormalize_(payload({class_name})).grade,class_name);
assert.equal(c.mwNormalize_(payload({parent_phone:'+972-50-0000000'})).phone,'0500000000');
assert.throws(()=>c.mwNormalize_(payload({school_name:'unlisted'})),/invalid_school/);assert.equal(c.mwNormalize_(payload({school_name:'אחר',school_other:'בית ספר בדיקה'})).school,'בית ספר בדיקה');
assert.equal(c.mwSafe_('=HYPERLINK("x")'),'\'=HYPERLINK("x")');
{const f=fixture(),catalog=c.mwCatalog_(f.ss);assert.deepEqual(Object.keys(catalog[0]),['id','name','price']);assert(!JSON.stringify(catalog).includes('secret'));}
// Form/server dropdowns must remain aligned, including the user-requested ז–יב range.
const html=fs.readFileSync('public/marathons/index.html','utf8');for(const [id,key] of [['class_name','MW_CLASSES'],['units','MW_LEVELS'],['school_name','MW_SCHOOLS']]){const choices=[...html.match(new RegExp('<select id="'+id+'"[^>]*>([\\s\\S]*?)</select>'))[1].matchAll(/<option value="([^"]*)"/g)].map(m=>m[1].replace(/&quot;/g,'"')).filter(x=>x&&x!=='אחר');assert.deepEqual(choices,[...c[key]]);}
{const f=fixture();for(let i=0;i<7;i++)c.mwIntake_(f.ss,c.mwNormalize_(payload({student_first_name:'תלמיד '+i})));for(let i=0;i<6;i++)c.mwAssign_(f.ss,{row:i+5,participantId:f.ps.rows[i+4][19],group:'group1'});assert.throws(()=>c.mwAssign_(f.ss,{row:11,participantId:f.ps.rows[10][19],group:'group1'}),/מלאה/);assert.equal(f.ps.rows[10][17],'ממתין לשיבוץ');assert.equal(f.ps.rows[4][8],80);f.ps.rows[4][11]=40;assert.throws(()=>c.mwAssign_(f.ss,{row:5,participantId:f.ps.rows[4][19],group:''}),/תשלום/);const g2=[...f.ev];g2[7]='group2';g2[8]='group2 | בדיקה';f.es.rows.push(g2);c.mwAssign_(f.ss,{row:5,participantId:f.ps.rows[4][19],group:'group2'});assert.equal(f.ps.rows[4][11],40);assert.equal(f.ps.rows[4][8],80);c.mwAssign_(f.ss,{row:11,participantId:f.ps.rows[10][19],group:'group1'});f.ps.rows[4][7]='כן';assert.throws(()=>c.mwAssign_(f.ss,{row:5,participantId:f.ps.rows[4][19],group:'group1'}),/נוכחות/);g2[9]='other-campaign';assert.throws(()=>c.mwAssign_(f.ss,{row:6,participantId:f.ps.rows[5][19],group:'group2'}),/אותו מרתון/);}
console.log('PASS: local campaign intake, pending assignment, six-seat capacity, group transfer, preserved price/payment, attended/paid restrictions, receipt recovery, duplicate/sibling handling, closed/changed-price campaigns, validation and dropdown parity.');
for(const email of ['', 'another@example.com']){c.Session={getActiveUser:()=>({getEmail:()=>email})};for(const fn of ['mwAdminState','mwAdminCreateCampaign','mwAdminCreateGroup','mwAdminAssign','mwAdminSetStatus','installMarathonManager','installMarathonWebIntake','openMarathonManager'])assert.throws(()=>c[fn]({}),/בעל החשבון/);}
c.Session={getActiveUser:()=>({getEmail:()=> 'ohadmath12@gmail.com'})};assert.doesNotThrow(()=>c.mwRequireOwner_());
console.log('PASS: anonymous and other-account calls cannot access administrative RPCs.');
